[package]
name = "alcomd-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true


[dependencies]
alcomd-domain.workspace = true
serde.workspace = true
tokio.workspace = true

[lints]
workspace = true
